CREATE DATABASE dtb_s02;
USE dtb_s02;


CREATE TABLE PRODUCTS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ProductName VARCHAR(100) NOT NULL,
    Price DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    Description TEXT
);